[package]
name    = "plotter-wasm"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
plotter            = { path = "../plotter-rs" }
serde              = { version = "1.0.228", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen       = "0.2.106"
